// Generated by CoffeeScript 1.11.1
(function() {
  var createMap, getStreamData, log, ready;

  log = function(x) {
    return console.log(x);
  };

  getStreamData = function() {
    return JSON.parse($("#streamData").text());
  };

  createMap = function() {
    var latings, map, polyline, streamData;
    $("#mapView").html("");
    streamData = getStreamData();
    latings = streamData[0].data;
    map = L.map("mapView", {
      center: latings[Math.round(latings.length / 2)],
      zoom: 10
    });
    return polyline = L.polyline(streamData[0].data, {
      color: "blue"
    }).addTo(map);
  };

  ready = function() {
    var waitForL, waitForLInterval;
    waitForL = function() {
      if (window.L) {
        createMap();
        return clearInterval(waitForLInterval);
      }
    };
    waitForLInterval = setInterval(waitForL, 300);
    return log("---> Ready");
  };

  document.addEventListener("DOMContentLoaded", ready);

  document.addEventListener("onreadystatechange", ready);

  document.addEventListener("page:load", ready);

  document.addEventListener("page:fetch", ready);

  document.addEventListener("page:receive", ready);

}).call(this);
